### PR TITLE
Allow custom_ops to work with non-leaf modules

### PR DESCRIPTION
**Pull request by myleott**
Some complex modules have children and non-negligible FLOPs themselves. One example of this is nn.MultiheadAttention, which includes children Linear modules, but also significant computation internally.

Unfortunately it's not possible to correctly define FLOPs for these modules because `custom_ops` is ignored for non-leaf modules.

After this fix it's possible to define: `custom_ops = {nn.MultiheadAttention: count_mha}` and have it work.

### CODE REVIEW

**Comment by Lyken17** [comment]
hi @myleott , thanks for your PR. I've noticed this issue before and write another counting function `profile_2`  in https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/profile.py#L130. Can you have a try?

**Comment by myleott** [comment]
Awesome, that works, thanks!

**Comment by Lyken17** [comment]
Glad to see it helps. I am doing more tests to ensure the `profile_2` has no bug and will switch to it in sometime this month.

**Comment by CharlesShang** [comment]
Hi @myleott, I have the same problem to profile `MultiheadAttention` layer. could you also share your custom_ops `count_mha`. 
much thanks!

**Pull request closed without merging**
