### PR TITLE
Fix issue #98

### LINKED ISSUE #98: MACs value becomes too large if there are shared modules
I think that the calculated MACs value becomes too large if there are shared modules.
The following is a script to reproduce this issue.
```python
from thop import profile
import torch
from torch import nn

class Net(nn.Module):
    def __init__(self, repeat=1):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        return self.linear(x)

def create_modules(share):
    m0 = Net()
    m1 = Net()
    m = nn.Sequential(m0, m1)
    if share:
        m1.linear = m0.linear
    return m

def measure(share):
    macs, params = profile(create_modules(share=share), (torch.randn(1, 10),))
    print("[share={}] macs={}, params={}".format(share, macs, params))

measure(True)
measure(False)
```

The execution result is shown below:
```console
$ python3 test.py
[share=True] macs=800.0, params=220.0
[share=False] macs=200.0, params=220.0
```

If `m0` and `m1` share the linear module, the MACs value is 800 but it should be the same as the non shared version (i.e., 200).

### PR DESCRIPTION
**Pull request by sile**
I'm not 100% sure that this PR doesn't introduce another problem but this can fix #98.
Feel free to close this PR if you have a better idea to address #98.

### CODE REVIEW

**Comment by lvmingzhe** [comment]
I think your answer is totally right and strongly recommend it.

**Comment by sile** [comment]
@lvmingzhe  Thank you for your comment. I merged the upstream master to resolve conflicts.

Although I'm not 100% sure that this patch is still valid as I don't catch up with the recent changes on this repository, a test run on my local machine using #98's example code has succeeded.

**Comment by saryazdi** [comment]
@sile I was facing the same issue:
```bash
torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'total_ops'
```
installed from your branch and it still works!:
```bash
pip3 install --upgrade git+https://github.com/sile/pytorch-OpCounter.git@8f115d4aeaee787d7347b75f30be28164b02ccaa
```

@lvmingzhe @Lyken17 would be great if this gets merged at some point

**Comment by sile** [comment]
Let me close this PR as it has not been reviewed by the author for a significant amount of time and I am no longer utilizing this library.

**Comment by dongfeicui** [comment]
> @sile I was facing the same issue:
> 
> ```shell
> torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'total_ops'
> ```
> 
> installed from your branch and it still works!:
> 
> ```shell
> pip3 install --upgrade git+https://github.com/sile/pytorch-OpCounter.git@8f115d4aeaee787d7347b75f30be28164b02ccaa
> ```
> 
> @lvmingzhe @Lyken17 would be great if this gets merged at some point

Traceback (most recent call last):
  File "/home/xhu/DentexSegAndDet/simple_infer.py", line 674, in <module>
    main()
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xhu/DentexSegAndDet/simple_infer.py", line 545, in main
    total_ops, total_params = profile(model, inputs=model_input) #, image_bgr_arr, image_gray_arr
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/thop/profile.py", line 240, in profile
    total_ops, total_params, ret_dict = dfs_count(model, set())
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/thop/profile.py", line 231, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, known, prefix=prefix + "\t")
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/thop/profile.py", line 231, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, known, prefix=prefix + "\t")
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/thop/profile.py", line 231, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, known, prefix=prefix + "\t")
  [Previous line repeated 2 more times]
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/thop/profile.py", line 218, in dfs_count
    total_ops, total_params = module.total_ops.item(), 0
  File "/home/xhu/software/miniconda3/envs/diffdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'total_ops'

It seems that I am still encountering this issue.

**Comment by dongfeicui** [comment]
Ultralytics contributed to the failure. This is my [solution](https://github.com/ultralytics/ultralytics/issues/7633#issue-2085744436).

**Pull request closed without merging**
